node {
 
 stage('Git CheckOut') {
    git branch: 'main', url: 'https://github.com/NaveenHL17/DevOps301-CaseStudy3.git'
 }
 
 def project_path="Jenkins/petclinic-code"
 
 dir(project_path) {
 
 stage('Maven Clean') {
    sh 'mvn clean'
 }
 
  stage('Maven Compile') {
    sh 'mvn compile'
 }
 
 stage('Maven Testing') {
    sh 'mvn test'
 }
 
 stage('Maven Package') {
    sh 'mvn package'
 }
 
 stage('Archive Artifacts') {
    archive 'target/*.war'
 }

 stage('Archive Artifacts') {
rtUpload (
    serverId: '1',
    spec: '''{
          "files": [
            {
              "pattern": "**/*.war",
              
            }
         ]
    }''',
 
    // Optional - Associate the uploaded files with the following custom build name and build number,
    // as build artifacts.
    // If not set, the files will be associated with the default build name and build number (i.e the
    // the Jenkins job name and number).
    buildName: 'petclinic',
    buildNumber: '1'
)

}
 }
}
